### ISSUE TITLE
Building branch with only one branch creates dirty exception

### ISSUE THREAD

**Issue by 20milliliter** [20milliliter/command-terminal#4]
The following code:
```gdscript
CommandServer.register_command(
    CommandBuilder.new()
        .Literal("foo")
        .Branch()
            .Literal("bar")
            .Callback(print, ["baz"])
        .EndBranch()
    .Build()
)
```
produces dirty exception:
`Trying to assign a value of type "Nil" to a variable of type "Array[ArgumentNode]".` @ `CommandBuilder.gd:68`

`CommandBuilder` contains an attempt to catch this error, but,
1. it doesn't work as is
2. its condition and assumed error would result in false positives

**Comment by tkim602** [comment]
Hi, can I give it a try for this issue?

**Comment by 20milliliter** [comment]
Sure. Just make sure that regular case (`Branch()`, `NextBranch()`, `EndBranch()`), single case (`Branch()`, `EndBranch()`), and invalid case (`EndBranch()`) all work as expected (no error, no error, error, respectively)

**Comment by tkim602** [comment]
@20milliliter Hi I tired to try this issue but I figured out that this is kind of beyond my abilities. I do not think I can handle this. Sorry.

**Comment by 20milliliter** [comment]
No worries, thank you for at least trying.
